export const capitalCities = [
  { city: 'Hargeisa', country: 'Somaliland', code: '' },
  { city: 'K. E. Point', country: 'South Georgia and South Sandwich Islands', code: 'GS' },
  { city: 'Mariehamn', country: 'Aland Islands', code: 'AX' },
  { city: 'Marigot', country: 'Saint Martin', code: 'MF' },
  { city: 'Kabul', country: 'Afghanistan', code: 'AF' },
  { city: 'Tirana', country: 'Albania', code: 'AL' },
  { city: 'Algiers', country: 'Algeria', code: 'DZ' },
  { city: 'Andorra la Vella', country: 'Andorra', code: 'AD' },
  { city: 'Luanda', country: 'Angola', code: 'AO' },
  { city: 'The Valley', country: 'Anguilla', code: 'AI' },
  { city: `Saint John's`, country: 'Antigua and Barbuda', code: 'AG' },
  { city: 'Buenos Aires', country: 'Argentina', code: 'AR' },
  { city: 'Yerevan', country: 'Armenia', code: 'AM' },
  { city: 'Oranjestad', country: 'Aruba', code: 'AW' },
  { city: 'Canberra', country: 'Australia', code: 'AU' },
  { city: 'Vienna', country: 'Austria', code: 'AT' },
  { city: 'Baku', country: 'Azerbaijan', code: 'AZ' },
  { city: 'Nassau', country: 'Bahamas', code: 'BS' },
  { city: 'Manama', country: 'Bahrain', code: 'BH' },
  { city: 'Dhaka', country: 'Bangladesh', code: 'BD' },
  { city: 'Bridgetown', country: 'Barbados', code: 'BB' },
  { city: 'Minsk', country: 'Belarus', code: 'BY' },
  { city: 'Brussels', country: 'Belgium', code: 'BE' },
  { city: 'Belmopan', country: 'Belize', code: 'BZ' },
  { city: 'Porto-Novo', country: 'Benin', code: 'BJ' },
  { city: 'Hamilton', country: 'Bermuda', code: 'BM' },
  { city: 'Thimphu', country: 'Bhutan', code: 'BT' },
  { city: 'La Paz', country: 'Bolivia', code: 'BO' },
  { city: 'Sarajevo', country: 'Bosnia and Herzegovina', code: 'BA' },
  { city: 'Gaborone', country: 'Botswana', code: 'BW' },
  { city: 'Brasilia', country: 'Brazil', code: 'BR' },
  { city: 'Road Town', country: 'British Virgin Islands', code: 'VG' },
  { city: 'Bandar Seri Begawan', country: 'Brunei Darussalam', code: 'BN' },
  { city: 'Sofia', country: 'Bulgaria', code: 'BG' },
  { city: 'Ouagadougou', country: 'Burkina Faso', code: 'BF' },
  { city: 'Rangoon', country: 'Myanmar', code: 'MM' },
  { city: 'Bujumbura', country: 'Burundi', code: 'BI' },
  { city: 'Phnom Penh', country: 'Cambodia', code: 'KH' },
  { city: 'Yaounde', country: 'Cameroon', code: 'CM' },
  { city: 'Ottawa', country: 'Canada', code: 'CA' },
  { city: 'Praia', country: 'Cape Verde', code: 'CV' },
  { city: 'George Town', country: 'Cayman Islands', code: 'KY' },
  { city: 'Santiago', country: 'Chile', code: 'CL' },
  { city: 'Beijing', country: 'China', code: 'CN' },
  { city: 'West Island', country: 'Cocos Islands', code: 'CC' },
  { city: 'Bogota', country: 'Colombia', code: 'CO' },
  { city: 'Moroni', country: 'Comoros', code: 'KM' },
  { city: 'Kinshasa', country: 'Democratic Republic of the Congo', code: 'CD' },
  { city: 'Brazzaville', country: 'Republic of Congo', code: 'CG' },
  { city: 'Avarua', country: 'Cook Islands', code: 'CK' },
  { city: 'San Jose', country: 'Costa Rica', code: 'CR' },
  { city: 'Yamoussoukro', country: `Cote d'Ivoire`, code: 'CI' },
  { city: 'Zagreb', country: 'Croatia', code: 'HR' },
  { city: 'Havana', country: 'Cuba', code: 'CU' },
  { city: 'Willemstad', country: 'CuraÃ§ao', code: 'CW' },
  { city: 'Nicosia', country: 'Cyprus', code: 'CY' },
  { city: 'Prague', country: 'Czech Republic', code: 'CZ' },
  { city: 'Copenhagen', country: 'Denmark', code: 'DK' },
  { city: 'Djibouti', country: 'Djibouti', code: 'DJ' },
  { city: 'Roseau', country: 'Dominica', code: 'DM' },
  { city: 'Santo Domi/go', country: 'Dominican Republic', code: 'DO' },
  { city: 'Quito', country: 'Ecuador', code: 'EC' },
  { city: 'Cairo', country: 'Egypt', code: 'EG' },
  { city: 'San Salvador', country: 'El Salvador', code: 'SV' },
  { city: 'Malabo', country: 'Equatorial Guinea', code: 'GQ' },
  { city: 'Asmara', country: 'Eritrea', code: 'ER' },
  { city: 'Tallinn', country: 'Estonia', code: 'EE' },
  { city: 'Addis Ababa', country: 'Ethiopia', code: 'ET' },
  { city: 'Stanley', country: 'Falkland Islands', code: 'FK' },
  { city: 'Torshavn', country: 'Faroe Islands', code: 'FO' },
  { city: 'Suva', country: 'Fiji', code: 'FJ' },
  { city: 'Helsinki', country: 'Finland', code: 'FI' },
  { city: 'Paris', country: 'France', code: 'FR' },
  { city: 'Papeete', country: 'French Polynesia', code: 'PF' },
  { city: 'Libreville', country: 'Gabon', code: 'GA' },
  { city: 'Banjul', country: 'The Gambia', code: 'GM' },
  { city: 'Tbilisi', country: 'Georgia', code: 'GE' },
  { city: 'Berlin', country: 'Germany', code: 'DE' },
  { city: 'Accra', country: 'Ghana', code: 'GH' },
  { city: 'Gibraltar', country: 'Gibraltar', code: 'GI' },
  { city: 'Athens', country: 'Greece', code: 'GR' },
  { city: 'Nuuk', country: 'Greenland', code: 'GL' },
  { city: `Saint George's`, country: 'Grenada', code: 'GD' },
  { city: 'Guatemala City', country: 'Guatemala', code: 'GT' },
  { city: 'Saint Peter Port', country: 'Guernsey', code: 'GG' },
  { city: 'Conakry', country: 'Guinea', code: 'GN' },
  { city: 'Bissau', country: 'Guinea-Bissau', code: 'GW' },
  { city: 'Georgetown', country: 'Guyana', code: 'GY' },
  { city: 'Port-au-Prince', country: 'Haiti', code: 'HT' },
  { city: 'Vatican City', country: 'Vatican City', code: 'VA' },
  { city: 'Tegucigalpa', country: 'Honduras', code: 'HN' },
  { city: 'Budapest', country: 'Hungary', code: 'HU' },
  { city: 'Reykjavik', country: 'Iceland', code: 'IS' },
  { city: 'New Delhi', country: 'India', code: 'IN' },
  { city: 'Jakarta', country: 'Indonesia', code: 'ID' },
  { city: 'Tehran', country: 'Iran', code: 'IR' },
  { city: 'Baghdad', country: 'Iraq', code: 'IQ' },
  { city: 'Dublin', country: 'Ireland', code: 'IE' },
  { city: 'Douglas', country: 'Isle of Man', code: 'IM' },
  { city: 'Jerusalem', country: 'Israel', code: 'IL' },
  { city: 'Rome', country: 'Italy', code: 'IT' },
  { city: 'Kingston', country: 'Jamaica', code: 'JM' },
  { city: 'Tokyo', country: 'Japan', code: 'JP' },
  { city: 'Amman', country: 'Jordan', code: 'JO' },
  { city: 'Astana', country: 'Kazakhstan', code: 'KZ' },
  { city: 'Nairobi', country: 'Kenya', code: 'KE' },
  { city: 'Pyongyang', country: 'North Korea', code: 'KP' },
  { city: 'Seoul', country: 'South Korea', code: 'KR' },
  { city: 'Pristina', country: 'Kosovo', code: 'KO' },
  { city: 'Kuwait City', country: 'Kuwait', code: 'KW' },
  { city: 'Bishkek', country: 'Kyrgyzstan', code: 'KG' },
  { city: 'Vientiane', country: 'Laos', code: 'LA' },
  { city: 'Riga', country: 'Latvia', code: 'LV' },
  { city: 'Beirut', country: 'Lebanon', code: 'LB' },
  { city: 'Maseru', country: 'Lesotho', code: 'LS' },
  { city: 'Monrovia', country: 'Liberia', code: 'LR' },
  { city: 'Tripoli', country: 'Libya', code: 'LY' },
  { city: 'Vaduz', country: 'Liechtenstein', code: 'LI' },
  { city: 'Vilnius', country: 'Lithuania', code: 'LT' },
  { city: 'Luxembourg', country: 'Luxembourg', code: 'LU' },
  { city: 'Skopje', country: 'Macedonia', code: 'MK' },
  { city: 'Antananarivo', country: 'Madagascar', code: 'MG' },
  { city: 'Lilongwe', country: 'Malawi', code: 'MW' },
  { city: 'Kuala Lumpur', country: 'Malaysia', code: 'MY' },
  { city: 'Male', country: 'Maldives', code: 'MV' },
  { city: 'Bamako', country: 'Mali', code: 'ML' },
  { city: 'Valletta', country: 'Malta', code: 'MT' },
  { city: 'Port Louis', country: 'Mauritius', code: 'MU' },
  { city: 'Mexico City', country: 'Mexico', code: 'MX' },
  { city: 'Chisinau', country: 'Moldova', code: 'MD' },
  { city: 'Monaco', country: 'Monaco', code: 'MC' },
  { city: 'Ulaanbaatar', country: 'Mongolia', code: 'MN' },
  { city: 'Podgorica', country: 'Montenegro', code: 'ME' },
  { city: 'Plymouth', country: 'Montserrat', code: 'MS' },
  { city: 'Rabat', country: 'Morocco', code: 'MA' },
  { city: 'Maputo', country: 'Mozambique', code: 'MZ' },
  { city: 'Windhoek', country: 'Namibia', code: 'NA' },
  { city: 'Kathmandu', country: 'Nepal', code: 'NP' },
  { city: 'Amsterdam', country: 'Netherlands', code: 'NL' },
  { city: 'Noumea', country: 'New Caledonia', code: 'NC' },
  { city: 'Wellington', country: 'New Zealand', code: 'NZ' },
  { city: 'Managua', country: 'Nicaragua', code: 'NI' },
  { city: 'Niamey', country: 'Niger', code: 'NE' },
  { city: 'Abuja', country: 'Nigeria', code: 'NG' },
  { city: 'Kingston', country: 'Norfolk Island', code: 'NF' },
  { city: 'Saipan', country: 'Northern Mariana Islands', code: 'MP' },
  { city: 'Oslo', country: 'Norway', code: 'NO' },
  { city: 'Muscat', country: 'Oman', code: 'OM' },
  { city: 'Islamabad', country: 'Pakistan', code: 'PK' },
  { city: 'Jerusalem', country: 'Palestine', code: 'PS' },
  { city: 'Panama City', country: 'Panama', code: 'PA' },
  { city: 'Port Moresby', country: 'Papua New Guinea', code: 'PG' },
  { city: 'Asuncion', country: 'Paraguay', code: 'PY' },
  { city: 'Lima', country: 'Peru', code: 'PE' },
  { city: 'Manila', country: 'Philippines', code: 'PH' },
  { city: 'Warsaw', country: 'Poland', code: 'PL' },
  { city: 'Lisbon', country: 'Portugal', code: 'PT' },
  { city: 'San Juan', country: 'Puerto Rico', code: 'PR' },
  { city: 'Doha', country: 'Qatar', code: 'QA' },
  { city: 'Bucharest', country: 'Romania', code: 'RO' },
  { city: 'Moscow', country: 'Russia', code: 'RU' },
  { city: 'Kigali', country: 'Rwanda', code: 'RW' },
  { city: 'Gustavia', country: 'Saint Barthelemy', code: 'BL' },
  { city: 'Jamestown', country: 'Saint Helena', code: 'SH' },
  { city: 'Basseterre', country: 'Saint Kitts and Nevis', code: 'KN' },
  { city: 'Castries', country: 'Saint Lucia', code: 'LC' },
  { city: 'Saint-Pierre', country: 'Saint Pierre and Miquelon', code: 'PM' },
  { city: 'Kingstown', country: 'Saint Vincent and the Grenadines', code: 'VC' },
  { city: 'Apia', country: 'Samoa', code: 'WS' },
  { city: 'San Marino', country: 'San Marino', code: 'SM' },
  { city: 'Sao Tome', country: 'Sao Tome and Principe', code: 'ST' },
  { city: 'Riyadh', country: 'Saudi Arabia', code: 'SA' },
  { city: 'Dakar', country: 'Senegal', code: 'SN' },
  { city: 'Belgrade', country: 'Serbia', code: 'RS' },
  { city: 'Victoria', country: 'Seychelles', code: 'SC' },
  { city: 'Freetown', country: 'Sierra Leone', code: 'SL' },
  { city: 'Singapore', country: 'Singapore', code: 'SG' },
  { city: 'Philipsburg', country: 'Sint Maarten', code: 'SX' },
  { city: 'Bratislava', country: 'Slovakia', code: 'SK' },
  { city: 'Ljubljana', country: 'Slovenia', code: 'SI' },
  { city: 'Honiara', country: 'Solomon Islands', code: 'SB' },
  { city: 'Mogadishu', country: 'Somalia', code: 'SO' },
  { city: 'Pretoria', country: 'South Africa', code: 'ZA' },
  { city: 'Juba', country: 'South Sudan', code: 'SS' },
  { city: 'Madrid', country: 'Spain', code: 'ES' },
  { city: 'Colombo', country: 'Sri Lanka', code: 'LK' },
  { city: 'Khartoum', country: 'Sudan', code: 'SD' },
  { city: 'Paramaribo', country: 'Suriname', code: 'SR' },
  { city: 'Longyearbyen', country: 'Svalbard', code: 'SJ' },
  { city: 'Mbabane', country: 'Swaziland', code: 'SZ' },
  { city: 'Stockholm', country: 'Sweden', code: 'SE' },
  { city: 'Bern', country: 'Switzerland', code: 'CH' },
  { city: 'Damascus', country: 'Syria', code: 'SY' },
  { city: 'Taipei', country: 'Taiwan', code: 'TW' },
  { city: 'Dushanbe', country: 'Tajikistan', code: 'TJ' },
  { city: 'Dar es Salaam', country: 'Tanzania', code: 'TZ' },
  { city: 'Bangkok', country: 'Thailand', code: 'TH' },
  { city: 'Dili', country: 'Timor-Leste', code: 'TL' },
  { city: 'Port of Spain', country: 'Trinidad and Tobago', code: 'TT' },
  { city: 'Tunis', country: 'Tunisia', code: 'TN' },
  { city: 'Ankara', country: 'Turkey', code: 'TR' },
  { city: 'Ashgabat', country: 'Turkmenistan', code: 'TM' },
  { city: 'Grand Turk', country: 'Turks and Caicos Islands', code: 'TC' },
  { city: 'Kampala', country: 'Uganda', code: 'UG' },
  { city: 'Kiev', country: 'Ukraine', code: 'UA' },
  { city: 'Abu Dhabi', country: 'United Arab Emirates', code: 'AE' },
  { city: 'London', country: 'United Kingdom', code: 'GB' },
  { city: 'Washington, D.C.', country: 'United States', code: 'US' },
  { city: 'Montevideo', country: 'Uruguay', code: 'UY' },
  { city: 'Tashkent', country: 'Uzbekistan', code: 'UZ' },
  { city: 'Port-Vila', country: 'Vanuatu', code: 'VU' },
  { city: 'Caracas', country: 'Venezuela', code: 'VE' },
  { city: 'Hanoi', country: 'Vietnam', code: 'VN' },
  { city: 'Charlotte Amalie', country: 'US Virgin Islands', code: 'VI' },
  { city: 'Sanaa', country: 'Yemen', code: 'YE' },
  { city: 'Lusaka', country: 'Zambia', code: 'ZM' },
  { city: 'Harare', country: 'Zimbabwe', code: 'ZW' },
  { city: 'North Nicosia', country: 'Northern Cyprus', code: '' },
  ];

export const randomIndexes = [6, 115, 172, 48, 54, 119, 61, 132, 21, 15, 188, 190, 118, 42, 114, 165, 155, 152, 166, 43, 134, 156, 176, 58, 104, 94, 60, 47, 161, 178, 187, 111, 147, 95, 5, 73, 167, 214, 164, 74, 169, 139, 35, 39, 24, 96, 200, 76, 202, 92, 163, 57, 68, 44, 182, 125, 149, 179, 195, 25, 86, 146, 112, 150, 36, 174, 168, 170, 100, 97, 153, 78, 138, 108, 136, 184, 102, 208, 186, 70, 210, 198, 191, 20, 22, 183, 88, 207, 29, 148, 1, 151, 80, 159, 189, 128, 0, 53, 98, 103, 89, 109, 113, 18, 19, 50, 87, 143, 215, 137, 212, 30, 173, 26, 77, 37, 101, 10, 192, 171, 38, 13, 99, 7, 204, 27, 217, 69, 196, 145, 185, 67, 56, 193, 199, 206, 65, 49, 33, 201, 130, 140, 160, 205, 181, 84, 2, 117, 71, 64, 175, 105, 197, 4, 107, 180, 106, 17, 72, 116, 157, 127, 209, 83, 158, 8, 14, 40, 23, 79, 216, 142, 126, 123, 81, 28, 154, 124, 90, 32, 211, 31, 45, 135, 177, 141, 144, 194, 46, 110, 63, 59, 11, 3, 66, 9, 120, 12, 162, 203, 129, 122, 85, 133, 121, 34, 52, 75, 213, 93, 51, 62, 91, 82, 16, 55, 41, 131];
  