export const capitalCities = [
    { city: 'Abu Dhabi', country: 'United Arab Emirates' },
    { city: 'Algiers', country: 'Algeria' },
    { city: 'Amman', country: 'Jordan' },
    { city: 'Amsterdam', country: 'Netherlands' },
    { city: 'Ankara', country: 'Turkey' },
    { city: 'Antananarivo', country: 'Madagascar' },
    { city: 'Apia', country: 'Samoa' },
    { city: 'Ashgabat', country: 'Turkmenistan' },
    { city: 'Asmara', country: 'Eritrea' },
    { city: 'Astana', country: 'Kazakhstan' },
    { city: 'Asuncion', country: 'Paraguay' },
    { city: 'Athens', country: 'Greece' },
    { city: 'Baghdad', country: 'Iraq' },
    { city: 'Baku', country: 'Azerbaijan' },
    { city: 'Bamako', country: 'Mali' },
    { city: 'Bandar Seri Begawan', country: 'Brunei' },
    { city: 'Bangkok', country: 'Thailand' },
    { city: 'Bangui', country: 'Central African Republic' },
    { city: 'Banjul', country: 'Gambia' },
    { city: 'Basseterre', country: 'Saint Kitts and Nevis' },
    { city: 'Beijing', country: 'China' },
    { city: 'Beirut', country: 'Lebanon' },
    { city: 'Belgrade', country: 'Serbia' },
    { city: 'Belmopan', country: 'Belize' },
    { city: 'Berlin', country: 'Germany' },
    { city: 'Bern', country: 'Switzerland' },
    { city: 'Bishkek', country: 'Kyrgyzstan' },
    { city: 'Bissau', country: 'Guinea-Bissau' },
    { city: 'Bogota', country: 'Colombia' },
    { city: 'Brasilia', country: 'Brazil' },
    { city: 'Bratislava', country: 'Slovakia' },
    { city: 'Brazzaville', country: 'Congo, Republic of the' },
    { city: 'Bridgetown', country: 'Barbados' },
    { city: 'Brussels', country: 'Belgium' },
    { city: 'Bucharest', country: 'Romania' },
    { city: 'Budapest', country: 'Hungary' },
    { city: 'Buenos Aires', country: 'Argentina' },
    { city: 'Cairo', country: 'Egypt' },
    { city: 'Canberra', country: 'Australia' },
    { city: 'Caracas', country: 'Venezuela' },
    { city: 'Castries', country: 'Saint Lucia' },
    { city: 'Chisinau', country: 'Moldova' },
    { city: 'Conakry', country: 'Guinea' },
    { city: 'Copenhagen', country: 'Denmark' },
    { city: 'Dakar', country: 'Senegal' },
    { city: 'Damascus', country: 'Syria' },
    { city: 'Dhaka', country: 'Bangladesh' },
    { city: 'Dili', country: 'East Timor' },
    { city: 'Djibouti', country: 'Djibouti' },
    { city: 'Dodoma', country: 'Tanzania' },
    { city: 'Dublin', country: 'Ireland' },
    { city: 'Dushanbe', country: 'Tajikistan' },
    { city: 'Edinburgh', country: 'Scotland' },
    { city: 'Helsinki', country: 'Finland' },
    { city: 'Honiara', country: 'Solomon Islands' },
    { city: 'Islamabad', country: 'Pakistan' },
    { city: 'Jakarta', country: 'Indonesia' },
    { city: 'Jerusalem', country: 'Israel' },
    { city: 'Kabul', country: 'Afghanistan' },
    { city: 'Kampala', country: 'Uganda' },
    { city: 'Kathmandu', country: 'Nepal' },
    { city: 'Kiev', country: 'Ukraine' },
    { city: 'Kingston', country: 'Jamaica' },
    { city: 'Kingstown', country: 'Saint Vincent and the Grenadines' },
    { city: 'Kinshasa', country: 'Congo, Democratic Republic of the' },
    { city: 'Kuala Lumpur', country: 'Malaysia' },
    { city: 'Kuwait City', country: 'Kuwait' },
    { city: 'Kyiv', country: 'Ukraine' },
    { city: 'La Paz', country: 'Bolivia' },
    { city: 'Libreville', country: 'Gabon' },
    { city: 'Lilongwe', country: 'Malawi' },
    { city: 'Lima', country: 'Peru' },
    { city: 'Lisbon', country: 'Portugal' },
    { city: 'Ljubljana', country: 'Slovenia' },
    { city: 'Lome', country: 'Togo' },
    { city: 'London', country: 'United Kingdom' },
    { city: 'Luanda', country: 'Angola' },
    { city: 'Lusaka', country: 'Zambia' },
    { city: 'Luxembourg', country: 'Luxembourg' },
    { city: 'Madrid', country: 'Spain' },
    { city: 'Majuro', country: 'Marshall Islands' },
    { city: 'Malabo', country: 'Equatorial Guinea' },
    { city: 'Male', country: 'Maldives' },
    { city: 'Managua', country: 'Nicaragua' },
    { city: 'Manama', country: 'Bahrain' },
    { city: 'Manila', country: 'Philippines' },
    { city: 'Maputo', country: 'Mozambique' },
    { city: 'Maseru', country: 'Lesotho' },
    { city: 'Mbabane', country: 'Eswatini (Swaziland)' },
    { city: 'Melekeok', country: 'Palau' },
    { city: 'Mexico City', country: 'Mexico' },
    { city: 'Minsk', country: 'Belarus' },
    { city: 'Mogadishu', country: 'Somalia' },
    { city: 'Monaco', country: 'Monaco' },
    { city: 'Monrovia', country: 'Liberia' },
    { city: 'Montevideo', country: 'Uruguay' },
    { city: 'Moroni', country: 'Comoros' },
    { city: 'Moscow', country: 'Russia' },
    { city: 'Muscat', country: 'Oman' },
    { city: 'Nairobi', country: 'Kenya' },
    { city: 'Nassau', country: 'Bahamas' },
    { city: 'Nay Pyi Taw', country: 'Myanmar (Burma)' },
    { city: 'NDjamena', country: 'Chad' },
    { city: 'New Delhi', country: 'India' },
    { city: 'Nicosia', country: 'Cyprus' },
    { city: 'Niamey', country: 'Niger' },
    { city: 'Nouakchott', country: 'Mauritania' },
    { city: 'Nuku\'alofa', country: 'Tonga' },
    { city: 'Oslo', country: 'Norway' },
    { city: 'Ottawa', country: 'Canada' },
    { city: 'Palikir', country: 'Federated States of Micronesia' },
    { city: 'Panama City', country: 'Panama' },
    { city: 'Paramaribo', country: 'Suriname' },
    { city: 'Paris', country: 'France' },
    { city: 'Podgorica', country: 'Montenegro' },
    { city: 'Port Louis', country: 'Mauritius' },
    { city: 'Port Moresby', country: 'Papua New Guinea' },
    { city: 'Port of Spain', country: 'Trinidad and Tobago' },
    { city: 'Port Vila', country: 'Vanuatu' },
    { city: 'Praia', country: 'Cape Verde' },
    { city: 'Pristina', country: 'Kosovo' },
    { city: 'Pyongyang', country: 'North Korea' },
    { city: 'Quito', country: 'Ecuador' },
    { city: 'Rabat', country: 'Morocco' },
    { city: 'Reykjavik', country: 'Iceland' },
    { city: 'Riga', country: 'Latvia' },
    { city: 'Riyadh', country: 'Saudi Arabia' },
    { city: 'Rome', country: 'Italy' },
    { city: 'Roseau', country: 'Dominica' },
    { city: 'San Jose', country: 'Costa Rica' },
    { city: 'San Marino', country: 'San Marino' },
    { city: 'San Salvador', country: 'El Salvador' },
    { city: 'Sana\'a', country: 'Yemen' },
    { city: 'Santiago', country: 'Chile' },
    { city: 'Santo Domingo', country: 'Dominican Republic' },
    { city: 'Sarajevo', country: 'Bosnia and Herzegovina' },
    { city: 'Skopje', country: 'North Macedonia (Macedonia)' },
    { city: 'Sofia', country: 'Bulgaria' },
    { city: 'Stockholm', country: 'Sweden' },
    { city: 'Sucre', country: 'Bolivia' },
    { city: 'Suva', country: 'Fiji' },
    { city: 'Taipei', country: 'Taiwan' },
    { city: 'Tallinn', country: 'Estonia' },
    { city: 'Tarawa Atoll', country: 'Kiribati' },
    { city: 'Tashkent', country: 'Uzbekistan' },
    { city: 'Tbilisi', country: 'Georgia' },
    { city: 'Tegucigalpa', country: 'Honduras' },
    { city: 'Tehran', country: 'Iran' },
    { city: 'Thimphu', country: 'Bhutan' },
    { city: 'Tirana', country: 'Albania' },
    { city: 'Tokyo', country: 'Japan' },
    { city: 'Tripoli', country: 'Libya' },
    { city: 'Tskhinvali', country: 'South Ossetia' },
    { city: 'Tunis', country: 'Tunisia' },
    { city: 'Ulaanbaatar', country: 'Mongolia' },
    { city: 'Vaduz', country: 'Liechtenstein' },
    { city: 'Valletta', country: 'Malta' },
    { city: 'Vatican City', country: 'Vatican City' },
    { city: 'Victoria', country: 'Seychelles' },
    { city: 'Vienna', country: 'Austria' },
    { city: 'Vientiane', country: 'Laos' },
    { city: 'Vilnius', country: 'Lithuania' },
    { city: 'Warsaw', country: 'Poland' },
    { city: 'Washington, D.C.', country: 'United States' },
    { city: 'Wellington', country: 'New Zealand' },
    { city: 'Windhoek', country: 'Namibia' },
    { city: 'Yamoussoukro', country: 'Ivory Coast' },
    { city: 'Yaounde', country: 'Cameroon' },
    { city: 'Yerevan', country: 'Armenia' },
    { city: 'Zagreb', country: 'Croatia' },
    { city: 'Zurich', country: 'Switzerland' }
  ];
  